### ISSUE TITLE
Games Search Page

### ISSUE THREAD

**Issue by EsotericZ** [EsotericZ/PSZReviews#3]
Clean to make look better
Once "heart" is selected auto update to new icon (successfully adds/removes from the db)
Add a toast notification when add/removed

**Comment by EsotericZ** [comment]
Search bar is fully working, searches on each key stroke. Need to clean up

**Comment by whats-a-pj** [comment]
adding modal functionality, needs tweaking to effectively fetch data though

**Comment by whats-a-pj** [comment]
data fetching for modal on this file is fixed!
modal is functional :)

**Comment by EsotericZ** [comment]
wishlist component fully functional!
