### ISSUE TITLE
RAWG Key Hidden

### ISSUE THREAD

**Issue by EsotericZ** [EsotericZ/PSZReviews#34]
Need to hide the RAWG key in every place used on the front end. There is a endpoint for it on the backend and it's hidden in an environmental variable. Create the connection - test and make sure it work as expected.

**Comment by whats-a-pj** [comment]
testing on the game search page, running into a cors error, going to try debugging

![Image](https://github.com/EsotericZ/PSZReviews/assets/132323565/082500dd-1379-432f-96c7-89e2b8635b63)
