### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by EsotericZ** [EsotericZ/PSZReviews#7]
Clean Page
Update how the style is? "Highlighted Game" on top then several under?
Make games clickable for more info

**Comment by whats-a-pj** [comment]
Got featured/highlighted game card layout. need to:

- change top margin to view img & details better
- make cards clickable
- grab the index of 1 for games following the featured game, with my current style it shows the featured game twice because it starts both grids at index 0

**Comment by whats-a-pj** [comment]
![Screenshot 2024-01-14 at 8 40 59 PM](https://github.com/EsotericZ/PSZReviews/assets/132323565/c892c01b-33fe-4a56-96b0-3a6fcfd4c58a)
featured game mock-up

**Comment by whats-a-pj** [comment]
going to continue trying to get the ... to overlay the left corner of the photo, and need to adjust how the photo displays. still need to make the cards themselves clickable

**Comment by whats-a-pj** [comment]
When logged in, username overlaps the game title. might move where the username displays or see how it looks with the title/scores on the left side.

**Comment by whats-a-pj** [comment]
- fix username display over featured game info
- live mas modal onclick

**Comment by whats-a-pj** [comment]
working on getting the game colors for each card atm

**Comment by EsotericZ** [comment]
Updated so the ADMIN selected game of the month is the featured game and the next 3 are admin selected "featured games"

**Comment by EsotericZ** [comment]
Finished the wishlist capabilities
